{% set name = "types-backports_abc" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-backports_abc-{{ version }}.tar.gz
  sha256: 7d71215c256dbe5e5376a304bdbed51476852053128eb56f9e541d5591496d6b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  commands:
    - test -f $SP_DIR/backports_abc-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for backports_abc
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
