{% set name = "types-backports_abc" %}
{% set version = "0.5.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-backports_abc-{{ version }}.tar.gz
  sha256: 4c35baaafafe1f5a06d0a6b3b080553c274a79071dfeb30bc2dd5a8633f8b65d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/backports_abc-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for backports_abc
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
